### ISSUE TITLE
Trouble using factorplot

### ISSUE THREAD

**Issue by atinesh** [elena-petrova/rossmann_TSA_forecasts#1]
Hello Elena, thanks for this beautiful notebook, It is very helpful. I was trying to run it but at line `In [25]:`

```
# sales trends
sns.factorplot(data = train_store, x = 'Month', y = "Sales", 
               col = 'StoreType', # per store type in cols
               palette = 'plasma',
               hue = 'StoreType',
               row = 'Promo', # per promo in the store in rows
               color = c)
```

I am getting below error

`ValueError: 'c' argument has 12 elements, which is not acceptable for use with 'x' with size 0, 'y' with size 0.`

**Comment by amisaada** [comment]
Bonjour avez-vous trouver la solution pour cette erreur moi aussi j'ai la même 
merci pour votre réponse car c'est très urgent pour moi

**Comment by atinesh** [comment]
> Bonjour avez-vous trouver la solution pour cette erreur moi aussi j'ai la même
> merci pour votre réponse car c'est très urgent pour moi

Sorry, I am still stuck

**Comment by atinesh** [comment]
Removed color properties to make it work

```
# sales trends
sns.factorplot(data = train_store, x = 'Month', y = "Sales", 
               col = 'StoreType', # per store type in cols
               row = 'Promo' # per promo in the store in rows)
```
